greeting:
  message: This is an user service on DEV env. (Config server's user-service-dev.yaml)

gateway:
  ip: 192.168.0.100

token:
  secret: my_secret_token_key_abcdefghijklnopqrstuvwxyz
  expiration-time: 36000000 # 10 hours in milliseconds
  